### ISSUE TITLE
gatsby develop gets stuck on 'source and transform nodes'

### ISSUE THREAD

**Issue by alexjorgef** [28development/gatsby-source-gitlab-api#1] opened 2021-08-03 03:45 UTC
## Steps to reproduce

1. Installed the package
2. Added it to my **gatsby-config.js** file
3. Run `gatsby develop`

## Result

```
...

success initialize cache - 0.040s
success copy gatsby files - 0.156s
success Compiling Gatsby Functions - 0.400s
success onPreBootstrap - 0.435s
success createSchemaCustomization - 0.083s
⠇ source and transform nodes
```

## Environment

* **OS**: Windows 10 x64 20H2 19042.1100
* **Shell**: CMD 10.0.19042.1110
* **Node**: 14.15.1
* **Yarn**: 1.22.5

yarn.lock

```
...

gatsby-source-gitlab-api@^1.0.5:
  version "1.0.5"
  resolved "https://registry.yarnpkg.com/gatsby-source-gitlab-api/-/gatsby-source-gitlab-api-1.0.5.tgz#0734ab542c235b149740b42e766f34e803afddfb"
  integrity sha512-vVs4SvkGgY2xaJZWsfaxUy33vRcOArhJtdHcei2i8tHTyleRdr8OYr8nVbTG9Yg829uHSFySC5x/VBEfAPNQcg==
  dependencies:
    "@gitbeaker/browser" "^28.0.4"
    "@gitbeaker/cli" "^28.0.4"
    "@gitbeaker/node" "^28.0.4"

...
```

package.json

```
...

  "dependencies": {
    "gatsby": "^3.8.0",
    "gatsby-image": "^3.8.0",
    "gatsby-plugin-google-analytics": "^3.8.0",
    "gatsby-plugin-manifest": "^3.8.0",
    "gatsby-plugin-offline": "^4.8.0",
    "gatsby-plugin-react-helmet": "^4.8.0",
    "gatsby-plugin-sharp": "^3.8.0",
    "gatsby-plugin-styled-components": "^4.8.0",
    "gatsby-remark-copy-linked-files": "^4.5.0",
    "gatsby-remark-images": "^5.5.0",
    "gatsby-remark-prismjs": "^5.5.0",
    "gatsby-remark-responsive-iframe": "^4.5.0",
    "gatsby-remark-smartypants": "^4.5.0",
    "gatsby-source-filesystem": "^3.8.0",
    "gatsby-source-github-api": "^1.0.0",
    "gatsby-source-gitlab-api": "^1.0.5",
    "gatsby-transformer-remark": "^4.5.0",
    "gatsby-transformer-sharp": "^3.8.0",
    "node-sass": "^6.0.1",
    "prismjs": "^1.20.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-github-btn": "^1.2.0",
    "react-github-button": "^0.1.11",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.2.0",
    "sharp": "^0.28.3",
    "styled-components": "^5.1.1"
  },
  "devDependencies": {
    "prettier": "2.3.2"
  },
  "resolutions": {
    "graphql": "^15.4.0",
    "graphql-compose": "^9.0.2",
    "webpack": "^5.24.2"
  },

...

```

## What I've tried

* `gatsby clean`
* Deleting .cache dir
* Deleting public dir
* Deleting node_modules dir
* Deleting yarn.lock file
* Reinstalling packages
* Resizing my terminal window (? weirdly something that seemed to work for some)

References: [@gatsbyjs/gatsby#17131](https://github.com/gatsbyjs/gatsby/issues/17131), [@gatsbyjs/gatsby#25216](https://github.com/gatsbyjs/gatsby/issues/25216), [@gatsbyjs/gatsby#28632](https://github.com/gatsbyjs/gatsby/issues/28632)

**Comment by guilleijo** [comment] 2021-08-13 16:29
@alex1a Hey Alexandre, were you able to fix this? I'm having the same problem, trying the same things to fix it without success.

**Comment by 28development** [comment] 2022-02-05 14:17
Any updates on this one, there is another reference that may help: https://github.com/gatsbyjs/gatsby/issues/28625

Unfortunately, I can't reproduce this, which is why I would close this for now. Let me know if there are any news for this case.

**Closed as completed by 28development** 2022-02-05 14:17 UTC

**Comment by alexjorgef** [comment] 2022-05-06 11:12
Hi again @28development, I dig a little deeper and find that the issue is from _gitbeaker_ dependency. Is not stuck but looped waiting for all requests to finish.
Instead using `const projects = await api.Projects.all();`, you should pass some pagination options to prevent requesting all GitLab projects. Something like `const projects = await api.Projects.all({ maxPages: 2, perPage: 40 });` will work. Thank you
